### ISSUE TITLE
Fabrication

### ISSUE THREAD

**Issue by rodneyosodo** [JKUATSES/audioAmplifier-2021#3]
fabricate an example of the design

**Comment by gich2009** [comment]
Fabrication is limited by the following TWO key issues:
1. Cost: the overall cost of the project may be about 1000 (with the most expensive material being the copper clad)
2. Time: an extension will be required for actual fabrication

**Comment by rodneyosodo** [comment]
I can help you find one copper clad to use

**Comment by rodneyosodo** [comment]
Upload the pdf file of the schematic
